# Mandapaka Venkata Bharath

## AI assignment 1

### Task - 1 Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.random.rand(4,4))
df

          0         1         2         3
0  0.521411  0.396396  0.761461  0.930446
1  0.456462  0.834853  0.884802  0.094479
2  0.033571  0.546151  0.583266  0.530352
3  0.205494  0.701809  0.112811  0.139812

### Task - 2 Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [3]:
df.columns=["Random value 1","Random value 2","Random value 3","Random value 4"]
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.521411        0.396396        0.761461        0.930446
1        0.456462        0.834853        0.884802        0.094479
2        0.033571        0.546151        0.583266        0.530352
3        0.205494        0.701809        0.112811        0.139812

### Task - 3 Find the descriptive statistics of the 'df' dataframe.

In [4]:
df.describe(include='all')

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.304234        0.619802        0.585585        0.423772
std          0.226088        0.190006        0.338617        0.390361
min          0.033571        0.396396        0.112811        0.094479
25%          0.162513        0.508712        0.465652        0.128478
50%          0.330978        0.623980        0.672363        0.335082
75%          0.472699        0.735070        0.792296        0.630376
max          0.521411        0.834853        0.884802        0.930446

### Task - 4 Check for the null values in 'df' and find the data type of the columns.

In [5]:
dict = {'C1':[10, 900, np.nan, 91],
        'C2': ["a", "b", "c", np.nan],
        'C3':[np.nan, 40, 80, 90]}
df1 = pd.DataFrame(dict)
df1

      C1   C2    C3
0   10.0    a   NaN
1  900.0    b  40.0
2    NaN    c  80.0
3   91.0  NaN  90.0

In [6]:
df1.isnull()

      C1     C2     C3
0  False  False   True
1  False  False  False
2   True  False  False
3  False   True  False

In [7]:
df1.isnull().sum()

C1    1
C2    1
C3    1
dtype: int64

In [8]:
df1["C1"].dtype, df1["C2"].dtype, df1["C3"].dtype,

(dtype('float64'), dtype('O'), dtype('float64'))

### Task - 5 Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [9]:
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.521411        0.396396        0.761461        0.930446
1        0.456462        0.834853        0.884802        0.094479
2        0.033571        0.546151        0.583266        0.530352
3        0.205494        0.701809        0.112811        0.139812

In [10]:
#using loc
df.loc[:,"Random value 2":"Random value 3"]

   Random value 2  Random value 3
0        0.396396        0.761461
1        0.834853        0.884802
2        0.546151        0.583266
3        0.701809        0.112811

In [11]:
#using iloc
df.iloc[:,1:3]

   Random value 2  Random value 3
0        0.396396        0.761461
1        0.834853        0.884802
2        0.546151        0.583266
3        0.701809        0.112811